#!/usr/bin/python
"""
Highly divisible triangular number
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

def trianglenumber(n):
	return .5 * n * (n + 1)

def trianglenumbers(n):
	num = []
	for i in range(1, n + 1):
		num.append(trianglenumber(i))
	return num
	
def tau(n):
        sqroot,t = int(n**0.5),0
        for factor in range(1,sqroot+1):
                if n % factor == 0:
                        t += 2
        if sqroot*sqroot == n: t = t - 1
        return t

def main():
	q = trianglenumbers(100000)
	for i in range(len(q)):
		if tau(q[i]) > 500:
			print(int(q[i]))
			break

if __name__ == "__main__":
	main()
