/* Highly divisible triangular number
 * Problem 12
 * The sequence of triangle numbers is generated by adding the natural
 * numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 +
 * 7 = 28. The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45,
 * 55, ... Let us list the factors of the first seven triangle numbers:
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five
 * divisors. What is the value of the first triangle number to have over
 * five hundred divisors? */
#include <stdio.h>
#include <math.h>

 int problem012()
 {
    int i = 0, j = 0, sum = 0, max = 0, num = 0, count = 0;

    for (i = 1; max <= 500; i++)
    {
        sum += i, num = (int)pow(sum, 0.5);

        for (j = 1; j < num + 1; j++)
            if (! (sum % j))
                count += 2;

        if (num * num == sum)
            count--;

        if (max < count)
            max = count;

        count = 0;
    }


    printf("%d\n", sum);

    return 0;
 }
