name: Dependency Submission

on:
  push:
    branches:
      - master

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  JAVA_VERSION: 21

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.1

      - name: Configure JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.4.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
