name: Publish Snapshot

on:
  push:
    branches:
      - master
    tags:
      - '**'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  JAVA_VERSION: 19

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'jaredsburrows/cs-interview-questions' && github.ref == 'refs/heads/master'

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.5.3

      - name: Configure JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3.11.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.5.0
        with:
          gradle-home-cache-cleanup: true

      - name: Run Asciidoctor
        run: ./gradlew asciidoctor testReport -s

      - name: Publish Website
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/docs/asciidoc
          user_name: "Github Actions"
          user_email: "action@github.com"
